import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
const root = 'C:\\sgSHIOK2026';
assert.equal(process.cwd(), root);
const label = process.argv[2] ?? 'focused';
assert.ok(['focused', 'all', 'docs'].includes(label));
const stamp = Date.now(), dir = resolve(root, 'qa/revamp-r1/weekly-metadata-20260914');
const files = label === 'focused' ? ['test_scheduled_source_metadata.py'] : label === 'docs' ? ['test_readme.py', 'test_agent_docs.py', 'test_repo_integrity.py'] : readdirSync(resolve(root, 'tests')).filter(p => /^test_source_.*\.py$/.test(p) || ['test_scheduled_source_metadata.py', 'test_readme.py', 'test_agent_docs.py', 'test_repo_integrity.py'].includes(p));
const paths = [...readdirSync(resolve(root, 'scripts')).filter(p => /^(source_metadata_|run_source_maintenance|check_source_metadata|acknowledge_source_notices|scheduled_source_metadata|inspect_source_notice)/.test(p)).map(p => 'scripts/' + p), ...files.map(p => 'tests/' + p), '.github/workflows/source-metadata-weekly.yml', 'README.md', 'AGENTS.md', 'NOTICE', '.vercelignore', '.gitignore'];
const hash = p => createHash('sha256').update(readFileSync(resolve(root, p))).digest('hex');
const sources = paths.map(path => ({path, sha256: hash(path)}));
const args = ['-B', '-m', 'pytest', ...files.map(p => 'tests/' + p), '-v', '--durations=10', '-p', 'no:cacheprovider', '--basetemp', resolve(root, 'tmp', `weekly-metadata-${stamp}`)];
const started = Date.now();
const result = spawnSync(resolve(root, '.venv/Scripts/python.exe'), args, {cwd:root, windowsHide:true, encoding:'utf8', timeout:label === 'all' ? 600000 : 300000, maxBuffer:4000000, env:{...process.env, PYTHONDONTWRITEBYTECODE:'1', TEMP:resolve(root,'tmp'), TMP:resolve(root,'tmp')}});
const unchanged = sources.every(s => hash(s.path) === s.sha256);
const receipt = {command:[resolve(root,'.venv/Scripts/python.exe'), ...args], exitCode:result.status, error:result.error?.message, stdout:result.stdout, stderr:result.stderr, elapsedMs:Date.now()-started, sources, sourcesUnchanged:unchanged, pipelineRuns:0};
const output = resolve(dir, `${label}-${stamp}.json`);
writeFileSync(output, JSON.stringify(receipt,null,2)+'\n', {flag:'wx'});
console.log(JSON.stringify({output,exitCode:result.status,sourcesUnchanged:unchanged,stdoutTail:result.stdout?.split(/\r?\n/).slice(-18).join('\n'),stderr:result.stderr}));
process.exitCode = result.status === 0 && unchanged ? 0 : 1;
