import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve, relative } from 'node:path';
import { hostname } from 'node:os';
import { gzipSync, gunzipSync } from 'node:zlib';
import { publicTrace } from '../legacy-reload-20260913/publish-trace.mjs';
const root='C:\\sgSHIOK2026';assert.equal(process.cwd(),root);
process.env.TEMP=process.env.TMP=resolve(root,'tmp');
const base='13487ead04115b4c732a7d0c8b0acab5922032ea',prefix='qa/revamp-r1/legacy-command-20260913',out=resolve(root,prefix);
const read=p=>readFileSync(resolve(root,p)),json=p=>JSON.parse(read(p)),sha=b=>createHash('sha256').update(b).digest('hex');
const write=(p,v)=>writeFileSync(resolve(out,p),JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const git=(...args)=>execFileSync('git',args,{cwd:root,windowsHide:true,maxBuffer:32000000});
assert.equal(git('rev-parse','HEAD').toString().trim(),base);
const checks=json(`${prefix}/checks-1789310489764.json`);assert.equal(checks.ok,true);
assert.ok(checks.runs[0].stdout.includes('tests 8')&&checks.runs[0].stdout.includes('pass 8'));
for(const s of checks.sources)assert.equal(sha(read(`${prefix}/${s.path}`)),s.sha256,s.path);
const reused='qa/revamp-r1/legacy-reload-20260913';
const prior=json(`${reused}/checks-v2-1789309002730.json`);assert.equal(prior.exitCode,0);
for(const s of prior.sources)assert.equal(sha(read(`${reused}/${s.path}`)),s.sha256);
const previousIndex=json(`${reused}/artifact-index.json`);
for(const p of ['publish-trace.mjs','publish-trace.test.mjs'])assert.equal(sha(read(`${reused}/${p}`)),previousIndex.files.find(f=>f.path===`${reused}/${p}`).sha256);
const previous='qa/revamp-r1/selection-recovery-20260913';
const build=json(`${previous}/build-2/build.json`),full=json(`${previous}/checks-lnq1fY/result.json`);
assert.equal(build.exitCode,0);assert.equal(full.exitCode,0);
const stdout=read(`${previous}/checks-lnq1fY/stdout.txt`).toString(),isolation=JSON.parse(stdout.slice(stdout.lastIndexOf('\n{')+1));
assert.ok(stdout.includes('1945 passed (1945)')&&stdout.includes('72 passed (72)')&&stdout.includes('pass 42'));
assert.equal(isolation.guardProbePassed,true);assert.equal(isolation.productionDataDirectoryAbsent,true);
for(const s of build.sources){assert.equal(sha(read(s.path)),s.sha256);assert.equal(sha(readFileSync(resolve(isolation.snapshot,s.path))),s.sha256);}
for(const s of full.sources)assert.equal(sha(read(s.path)),s.sha256);
assert.equal(json(`${previous}/checks-1l0OqM/result.json`).exitCode,0);
const anchors=Object.values(json('web/lib/__tests__/fixtures/published-walks.provenance.json').sources).map(s=>{
  const b=read(s.path);assert.equal(sha(b),s.sha256,'STOP input mismatch '+s.path);assert.equal(b.length,s.bytes);return{path:s.path,sha256:sha(b),bytes:b.length};
});
const weightSha256=sha(read('pipeline/config/weights.yaml'));assert.equal(weightSha256,'5c62ac5f62e91f777a82f0dfa98eafba11ef47500c9f7822a81a31eae7d2cbec');
assert.equal(git('diff','--name-only',base,'--','web','pipeline','raw','processed','checksums.json','qa/p6_*','qa/p7_*','qa/p8_*','qa/p9_*','qa/p10_*','qa/p11/d_*','qa/releases').toString().trim(),'');
const start=Date.now(),r=spawnSync('python',['-B','scripts/check_repo_integrity.py'],{cwd:root,windowsHide:true,encoding:'utf8',timeout:60000});
const integrity={command:['python','-B','scripts/check_repo_integrity.py'],exitCode:r.status,stdout:r.stdout,stderr:r.stderr,elapsedMs:Date.now()-start};write('integrity.json',integrity);assert.equal(r.status,0);assert.ok(r.stdout.includes('repo_integrity=ok'));
const evidence='qa/verification/REVAMP-R1-core-walk.md',before=git('show',`${base}:${evidence}`),after=read(evidence);
assert.equal(before.length,415052);assert.equal(Buffer.compare(before,after.subarray(0,before.length)),0);assert.ok(after.length>before.length);
assert.ok(after.subarray(before.length).includes('FINDINGS')&&after.subarray(before.length).includes('DISAGREEMENTS'));
const ignore=spawnSync('git',['check-ignore','-v',evidence,`${prefix}/summary.json`],{cwd:root,windowsHide:true,encoding:'utf8'});assert.equal(ignore.status,1);
assert.equal(git('ls-files','--',evidence).toString().trim(),evidence);
write('tracking.json',{command:['git','check-ignore','-v',evidence,`${prefix}/summary.json`],exitCode:ignore.status,stdout:ignore.stdout,stderr:ignore.stderr,evidenceTracked:true,newArtifacts:'Explicit staging/index check follows'});
const directory='observed-h3J563',raw=read(`${prefix}/${directory}/browser.json`),browser=JSON.parse(raw),supervisor=json(`${prefix}/${directory}/supervisor.json`);
assert.equal(browser.ok,false);assert.equal(supervisor.exitCode,1);assert.equal(supervisor.cleanup.verified,true);assert.equal(browser.chromeTerminal.code,0);
assert.equal(browser.finalBoundsClear,true);assert.equal(browser.anchorsUnchanged,true);assert.equal(browser.server.releaseSwitches,0);assert.equal(browser.commandDiagnostics.pending,0);
const command25=browser.commandDiagnostics.entries.find(c=>c.id===25),probe26=browser.commandDiagnostics.entries.find(c=>c.id===26);
assert.equal(command25.outcome,'timeout');assert.equal(command25.lateReplies,1);assert.equal(command25.lastLateReplyMs-command25.startedMs,10962);assert.equal(probe26.outcome,'response');
const published=publicTrace(browser),bytes=Buffer.from(JSON.stringify(published.trace,null,2)+'\n'),gz=gzipSync(bytes);assert.equal(Buffer.compare(gunzipSync(gz),bytes),0);
writeFileSync(resolve(out,directory,'browser.public.json.gz'),gz,{flag:'wx'});
const traceIdentity={raw:{bytes:raw.length,sha256:sha(raw),published:false,reason:'Raw event cookies/address headers; retained local'},public:{file:'browser.public.json.gz',bytes:bytes.length,sha256:sha(bytes),compressedBytes:gz.length,compressedSha256:sha(gz),redactions:published.redactions}};
const {events,...receipt}=published.trace;write(`${directory}/receipt.json`,{...receipt,eventCount:events.length,traceIdentity});
const captures=readdirSync(resolve(out,directory)).filter(n=>n.endsWith('.png')).map(name=>{
  const b=read(`${prefix}/${directory}/${name}`),bracket=browser.captures.find(c=>c.name+'.png'===name),expected=bracket??browser.unbracketedCapture;
  assert.equal(sha(b),expected.sha256);return{path:`${directory}/${name}`,bytes:b.length,sha256:sha(b),completedBracket:!!bracket,parentInspected:true};
});assert.equal(captures.length,2);
const retired=json(`${prefix}/preview-retirement-readback.json`);assert.ok(!retired.processes.some(p=>[22016,32160].includes(p.ProcessId)));
for(const id of [37188,5816,33360,35540])assert.ok(retired.processes.some(p=>p.ProcessId===id));
const preview=await(await fetch('http://127.0.0.1:4420/__qa/status',{signal:AbortSignal.timeout(10000)})).json();assert.equal(preview.buildId,build.buildId);assert.equal(preview.readOnlyData,true);
const board=Buffer.from(await(await fetch('http://127.0.0.1:4420/postplan.html',{signal:AbortSignal.timeout(10000)})).arrayBuffer());assert.equal(sha(board),sha(read('postplan.html')));
const findings=['Timed-out preservation setup received a late reply; Browser.getVersion responded. Lost browser connection does not explain this wait.','No release switch or acceptance; discarded late payload cannot prove operation success.','Retired obsolete4418 preview, retained current4420/shared4340; no performance-causation claim.','Independent audit prioritizes already-authorized T14 lifecycle and inactiveT23 integration; real services/physical/release gates remain.'];
const disagreements=['Late reply is not successful completion; keep failed diagnostic and exact timings.','More browser replay is not the next product priority while authorized implementation remains.'];
const summary={root,hostname:hostname(),base,createdAt:new Date().toISOString(),goal:'ACTIVE',productSourceChanges:0,tests:{newDiagnostics:8,retainedHarness:15,retainedPublication:2,retainedWeb:{tests:1945,files:72,guards:42,rerun:false},retainedPython:{tests:1012,files:12,rerun:false},integrityExit:r.status},build:{buildId:build.buildId,sources:build.sources.length,currentTestAndBuildMatch:true,deploymentIdentityVerified:false},browser:{directory,ok:false,checks:browser.checks.length,passed:browser.checks.filter(c=>c.pass).length,releaseSwitches:0,supervisorMs:supervisor.elapsedMs,driverMs:browser.elapsedMs,command25,probe26,captures,traceIdentity,cleanup:true,finalBoundsClear:true,chromeExit:0},arithmetic:'39398-28436=10962ms late reply;38447-28436=10011ms timeout;39398-38447=951ms later.1browser=51.947s supervisor;2images.',evidence:{path:evidence,previousBytes:before.length,previousSha256:sha(before),bytes:after.length,addedBytes:after.length-before.length,exactPrefix:true},anchors,weightSha256,preview,taskBoard:{url:'http://127.0.0.1:4420/postplan.html',sha256:sha(board)},review:json(`${prefix}/review.json`),completionGates:json(`${prefix}/completion-gates.json`),findings,disagreements,pipelineRuns:0,pipelineSeconds:0,installations:0,deployments:0};write('summary.json',summary);
const files=[];
function walk(dir){for(const e of readdirSync(dir,{withFileTypes:true})){const path=resolve(dir,e.name);if(e.isDirectory())walk(path);else{const name=relative(out,path).replaceAll('\\','/');if(name.endsWith('/browser.json'))continue;const b=readFileSync(path);files.push({path:`${prefix}/${name}`,bytes:b.length,sha256:sha(b)});}}}
walk(out);write('artifact-index.json',{files});write('stage-paths.json',[...files.map(f=>f.path),`${prefix}/artifact-index.json`,`${prefix}/stage-paths.json`]);
console.log(JSON.stringify({newTests:8,browserAccepted:false,checks:summary.browser.checks,supervisorMs:supervisor.elapsedMs,evidence:summary.evidence,sourceCount:build.sources.length,anchors:anchors.length,integrityExit:r.status,checkIgnoreExit:ignore.status,artifacts:files.length},null,2));
