import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
const root = 'C:\\sgSHIOK2026';
if (process.cwd() !== root) throw Error('Wrong working root');
const directory = resolve(root, 'qa/revamp-r1/automatic-upgrade-20260909');
const bytes = readFileSync(resolve(directory, 'summary.json')), report = JSON.parse(bytes);
console.log('working_root=' + root + '\nhostname=' + process.env.COMPUTERNAME + '\nbase=' + report.base);
console.log('summary_sha256=' + createHash('sha256').update(bytes).digest('hex'));
console.log('browser_receipt=' + report.browser.receipt + '\nbrowser_ok=' + report.browser.ok);
console.log('browser_checks=27 passed + 0 failed = 27\ncaptures=2 A + 2 B = 4; all inspected at390x844');
console.log('browser_elapsed_ms=' + report.browser.elapsedMs + '; functional test only, not a latency benchmark');
for (const document of report.browser.documents) console.log(JSON.stringify(document));
console.log('controller_observed_after_origin_switch_ms=' + report.browser.controller.elapsedMs);
console.log('cached_data_retained=6\ncached_A_JS_retained=12\nretained_data_plus_JS=6 + 12 = 18');
console.log('old_JS_origin404=12/12\nforeign_and_future_sentinels=2/2\npersisted_page_errors=' + report.browser.pageErrors.length);
console.log('browser_cleanup_verified=' + report.browser.cleanupVerified + '\nproxy_retirement_confirmed=' + report.retirementConfirmed.ok);
console.log('user_preview=' + report.userPreview);
console.log('web_tests=1441\nweb_test_files=56\ntest_delta=1441 - 1441 = 0\nfile_delta=56 - 56 = 0');
console.log('full_test_receipt=' + report.tests.receipt);
for (const command of report.tests.commands) console.log('exit=' + command.exitCode + ' command=' + command.command + ' ' + command.args.join(' '));
console.log('build_reused=' + report.build.buildId + '\nbuilt_source_matches=132/132\nprotected_source_anchors=11/11');
console.log('review_qualification=' + readFileSync(resolve(directory, 'review-qualification.json'), 'utf8').trim());
console.log('FINDINGS');
report.findings.forEach((finding, index) => console.log((index + 1) + '. ' + finding));
console.log('DISAGREEMENTS');
report.disagreements.forEach((finding, index) => console.log((index + 1) + '. ' + finding));
console.log('pre_append_evidence_bytes=' + report.evidencePrefix.bytes + '\npre_append_evidence_sha256=' + report.evidencePrefix.sha256 + '\npre_append_prefix_unchanged=' + report.evidencePrefix.unchanged);
console.log('pipeline_runs=0\npipeline_cost=$0\ninstallations=0\ndeployment_commands=0\nprotected_payload_mutations=0\nweights_yaml_changes=0\nX_operations=0');
